language: php
php:
- 7.0
- 7.1
- 7.2
env:
- WP_VERSION=4.9
- WP_VERSION=latest
before_script:
- composer global require "phpunit/phpunit:6.*"
- composer global require wp-coding-standards/wpcs
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
- bash bin/install-wp-tests.sh $WP_VERSION
script:
- phpcs
- phpunit
